services:
  db:
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_PASSWORD: calypso

  web:
    build: .
    ports:
      - 3000:3000
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://db:5432/postgres"
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: calypso
      APPLICATION_URL: http://localhost:3000
      LOGIN_FRONTEND_URL: http://localhost:7002/
      LOGIN_API_URL: http://nyckeln:7002/
      LOGIN_KEY: asdf
      HIVE_URL: http://nyckeln:7004
      HIVE_API_KEY: skibidi-development
      DARKMODE_URL: false
      PORT: 3000
  nyckeln:
    image: ghcr.io/datasektionen/nyckeln-under-dorrmattan
    environment:
      KTH_ID: turetek #set me to switch user! If you want to view everything, use "turetek"
    configs:
      - source: nyckeln.yaml
        target: /config.yaml
    ports:
      - 7002:7002
      - 7003:7003
      - 7004:7004

configs:
  nginx.conf:
    content: | 
      events {}

      http {
        server {
          listen 7003;

          location / {
            proxy_pass http://nyckeln:7003;
          }
        }
      }
  
  nyckeln.yaml: #To update these perms, remove container `docker ps -a` and `docker rm -vf <image hash>` and remove image with `docker rmi -f ghcr.io/datasektionen/nyckeln-under-dorrmattan`
    content: |
      clients:
        - id: "client-id" # use this in your oidc client
          secret: "client-secret" # use this in your oidc client
          redirect_uris: # URIs of your oidc client
            [
              "http://localhost:4000/oidcc/callback",
              "http://localhost:4000/oidcc/authorize",
            ]

      users:
        - ug_kth_id: some-id
          kth_id: turetek
          email: turetek@kth.se
          first_name: Ture
          family_name: Teknolog
          pls_permissions:
            calypso:
              - drek
              - dfunk
          hive_tags:
            - id: personal_email
              content: turetek@gmail.com
      hive:
        tokens:
          - secret: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa
            permissions:
              - id: admin
                scope: null
        groups:
          - name: Systemansvarig
            id: d-sys
            domain: example.com
            members:
              - turetek
            tags:
              - id: author-pseudonym
                content: D-Sys
              - id: mandate
            permissions: 
              - id: post
                scope: "*"
              - id: manage-all
                scope: "*"
              - id: mark-important
                scope: "*"

