version: "3.8"
services:
  db:
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_PASSWORD: calypso

  web:
    build: .
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://db:5432/postgres"
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: calypso
      APPLICATION_URL: http://localhost.datasektionen.se:3000
    env_file: .env
    ports:
      - "3000:8080"
