security.basic.enabled=false
spring.main.allow-circular-references=true
spring.jpa.generate-ddl=true
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
server.port=${PORT:8080}
server.error.include-message=ALWAYS

spring.security.oauth2.client.registration.datasektionen.client-id=${OIDC_ID}
spring.security.oauth2.client.registration.datasektionen.client-secret=${OIDC_SECRET}
spring.security.oauth2.client.registration.datasektionen.scope=openid,profile,email,permissions,picture
spring.security.oauth2.client.provider.datasektionen.issuer-uri=${OIDC_PROVIDER}
